[tool.pytest.ini_options]
# Directories where tests live
testpaths = ["tests"]
# Verbose output
addopts = "-v"
# Files to recognize as test files
python_files = "test_*.py"

[tool.flake8]
# Maximum line length for code
max-line-length = 88
# Directories/files to exclude from linting
exclude = [".venv", "__pycache__", "build", "dist", ".git"]
# Relax type annotation and import rules for test files
per-file-ignores = [
    "tests/*:F401,ANN201,ANN001,ANN401",  # Allow unused imports, missing return types, missing arg types, and Any usage in tests
]
extend-ignore = [
    "E203",  # Whitespace before ':' (conflicts with Black formatter)
    "W503",  # Line break before binary operator (old style)
    "ANN101", # Missing type annotation for 'self' (redundant)
    "ANN102", # Missing type annotation for 'cls' (redundant)
]

[tool.mypy]
python_version = "3.11"
# Require type annotations for variables
disallow_untyped_defs = true
disallow_any_unimported = true
disallow_incomplete_defs = true
show_error_codes = true
