#!/usr/bin/env bash

set -e

VENV_DIR=".venv"
VENV_PYTHON="$VENV_DIR/bin/python3"

function print_usage {
  echo "Usage: ./run install | test | /absolute/path/to/file"
}

function run_install {
  bash setup.sh
}

function run_test {
  if [ ! -f "$VENV_PYTHON" ]; then
    echo "Error: Virtual environment not found. Run './run.sh install' first."
    exit 1
  fi

  source $VENV_DIR/bin/activate

  "$VENV_PYTHON" -m coverage run -m pytest -v tests/ || true
  "$VENV_PYTHON" -m coverage report
}

function run_program {
  local file_path="$1"
  if [ ! -f "$VENV_PYTHON" ]; then
    echo "Error: Virtual environment not found. Run './run.sh install' first."
    exit 1
  fi

  source $VENV_DIR/bin/activate

  "$VENV_PYTHON" -m src.commands.catalogue_runner "$file_path"
}

# ---- Main ----

if [ $# -ne 1 ]; then
  print_usage
  exit 1
fi

ARG="$1"

case "$ARG" in
  install)
    run_install
    ;;
  test)
    run_test
    ;;
  /*)
    run_program "$ARG"
    ;;
  *)
    print_usage
    exit 1
    ;;
esac

